=== ThomasKlengel/ProContrA/ProContrA/ConfigFiles/process.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Process" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="IpAddress">
    <xs:restriction base="xs:string">
      <xs:pattern value="(([1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Path">
    <xs:restriction base="xs:string">
      <xs:pattern value="([a-zA-Z]:|\.{2})(\\([^/:*?&lt;&gt;&quot;|]*(?&lt;![ ]))+)*\\+" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Group"/>
      <xs:enumeration value="Logical"/>      
      <xs:enumeration value="Storage"/>
      <xs:enumeration value="Tool"/>      
    </xs:restriction>
  </xs:simpleType>
  <!-- Resources-->
  <xs:element name="Resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Resource" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Resource">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SkillDefinitions" minOccurs="0"/>
        <xs:element ref="States" minOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required" />
      <xs:attribute name="Type" type="Type" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="States">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="State" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="State">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Conditions" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ID" type="xs:integer" use="required" />
      <xs:attribute name="Name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <!-- Skills-->
  <xs:element name="SkillDefinitions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SkillDefinition" minOccurs="1"  maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SkillDefinition">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="StartConditions" minOccurs="0" />
        <xs:element ref="ActiveConditions" minOccurs="0" />
        <xs:element ref="FinishedConditions" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Parameters" type="xs:string" use="optional"/>
      <xs:attribute name="TimeRequired" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
  <!-- An Element representing the execution of a single Skill -->
  <xs:element name="SkillExecution">
    <xs:complexType>
      <xs:attribute name="Resource" type="xs:string" use="required" />
      <xs:attribute name="Name" type="xs:string" use="required" />
      <xs:attribute name="Parameters" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <!-- Conditions-->
  <xs:element name="StartConditions">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0"  maxOccurs="unbounded">
          <xs:element ref="Condition" minOccurs="0"  maxOccurs="unbounded"/>
          <xs:element ref="BooleanCondition" minOccurs="0"  maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ActiveConditions">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0"  maxOccurs="unbounded">
          <xs:element ref="Condition" minOccurs="0"  maxOccurs="unbounded"/>
          <xs:element ref="BooleanCondition" minOccurs="0"  maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FinishedConditions">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Condition" minOccurs="0"  maxOccurs="unbounded"/>
          <xs:element ref="BooleanCondition" minOccurs="0"  maxOccurs="unbounded"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Conditions">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element ref="Condition" minOccurs="0"  maxOccurs="unbounded"/>
          <xs:element ref="BooleanCondition" minOccurs="0"  maxOccurs="unbounded"/>
        </xs:choice>        
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Condition">
    <xs:complexType>
      <xs:attribute name="Statement" type="xs:string" use="optional"/>
      <xs:attribute name="Resource" type="xs:string" use="optional" />
      <xs:attribute name="State" type="xs:string" use="optional" />
      <xs:attribute name="BoolValue" type="xs:boolean" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="BooleanCondition">
    <xs:complexType>
    <xs:sequence>
        <xs:element ref="Condition" minOccurs="2" maxOccurs="unbounded"/>      
    </xs:sequence>
      <xs:attribute name="Type" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <!-- Process-->
  <xs:element name="RunProcess">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Sequence" minOccurs="1" maxOccurs="unbounded" />
        <xs:element ref="Process" minOccurs="1" maxOccurs="unbounded"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <!-- An Element representing a Skill that runs its SubSkills sequentially -->
  <xs:element name="Sequence">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="SkillExecution" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="Sequence" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>      
      <xs:attribute name="Resource" type="xs:string" use="required" />
      <xs:attribute name="Name" type="xs:string" use="required" />
      <xs:attribute name="Parameters" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  <!--An Element representing a Skill that runs its SubSkills in parallel-->
  <xs:element name="Process">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded" >
        <xs:element ref="SkillExecution" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="Sequence" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="Process" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute name="Resource" type="xs:string" use="required" />
      <xs:attribute name="Name" type="xs:string" use="required" />
      <xs:attribute name="Parameters" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Main">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Resources" minOccurs="1" maxOccurs="unbounded" />
        <xs:element ref="RunProcess" minOccurs="1" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:attribute name="Name" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ThomasKlengel/ProContrA/ProContrA/ConfigFiles/ProContraProcess.xml
<?xml version="1.0" encoding="utf-8"?>
<Main Name="FASMAMOS2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="process.xsd">
  <Resources>
    <Resource Name="Part" Type="Logical">
      <States>
        <State ID="1" Name="IO"/>
      </States>
    </Resource>

    <Resource Name="Gripper" Type="Tool">
      <SkillDefinitions>
        <SkillDefinition Name="Open" TimeRequired="100">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="false" />
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Closed" BoolValue="false" />
            <Condition Resource="Self" State="Open" BoolValue="true" />
            <!--Same as 2 above conditions-->
            <Condition Statement="Self|Closed==false
                              OR Self|Open==true AND (Self|Closed==false
                              OR Self|Open==false)"/>
          </FinishedConditions>
        </SkillDefinition>
        <SkillDefinition Name="Close" TimeRequired="100">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="false" />
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Closed" BoolValue="true" />
            <Condition Resource="Self" State="Open" BoolValue="false" />
          </FinishedConditions>
        </SkillDefinition>
        <SkillDefinition Name="ErrorQuit" TimeRequired="500">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Error" BoolValue="false"/>
          </FinishedConditions>
        </SkillDefinition>
      </SkillDefinitions>
      <States>
        <State ID="-1" Name="Error"/>
        <State ID="0" Name="Undefined"/>
        <State ID="1" Name="Opened"/>
        <State ID="2" Name="Closed"/>
      </States>
    </Resource>
    <Resource Name="SCARA" Type="Tool">
      <SkillDefinitions>
        <SkillDefinition Name="MoveHome" Parameters="PathNumber" TimeRequired="500">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="false" />
            <Condition Resource="Self" State="Moving" BoolValue="false" />
            <Condition Resource="Self" State="InPosition" BoolValue="true" />
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Moving" BoolValue="false" />
            <Condition Resource="Self" State="InPosition" BoolValue="true" />
            <Condition Resource="Self" State="Position == Home" BoolValue="true"/>
            <!--Home Position mÃ¶glicherweise als virtuelle Resource?-->
          </FinishedConditions>
        </SkillDefinition>
        <SkillDefinition Name="Move" Parameters="Source,Target,PathNumber" TimeRequired="500">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="false" />
            <Condition Resource="Self" State="Moving" BoolValue="false" />
            <Condition Resource="Self" State="InPosition" BoolValue="true" />
            <Condition Resource="Self" State="Position" BoolValue="Source.Position"/>
            <Condition Resource="Target" State="IsOccupied" BoolValue="false"/>
            <Condition Resource="Target" State="InPosition" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Moving" BoolValue="false" />
            <Condition Resource="Self" State="InPosition" BoolValue="true" />
            <Condition Resource="Self" State="Position == Target" BoolValue="true"/>
          </FinishedConditions>
        </SkillDefinition>
        <SkillDefinition Name="ErrorQuit" TimeRequired="1000">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Error" BoolValue="false"/>
          </FinishedConditions>
        </SkillDefinition>
      </SkillDefinitions>
      <States>
        <State ID="-1" Name="Error"/>
        <State ID="0" Name="InPosition"/>
        <State ID="1" Name="Moving"/>
      </States>
    </Resource>

    <Resource Name="Nest01" Type="Storage">
      <States>
        <State Name ="Empty" ID="0"/>
        <State Name="Occupied" ID="1"/>
      </States>
    </Resource>
    <Resource Name="Nest06" Type="Storage">
      <States>
        <State Name ="Empty" ID="0"/>
        <State Name="Occupied" ID="1"/>
      </States>
    </Resource>
    <Resource Name="Tray" Type="Storage">
      <States>
        <State Name ="Empty" ID="0"/>
        <State Name="Occupied" ID="1"/>
      </States>
    </Resource>

    <Resource Name="Seperation" Type="Tool">
      <SkillDefinitions>
        <SkillDefinition Name="Seperate" Parameters="" TimeRequired="200">
          <StartConditions>
            <Condition Resource="Self" State="AtSeperation" BoolValue="false"/>
            <Condition Resource="Self" State="PartPresent" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="AtSeperation" BoolValue="true"/>
          </FinishedConditions>
        </SkillDefinition>
        <SkillDefinition Name="Input" Parameters="" TimeRequired="200">
          <StartConditions>
            <Condition Resource="Self" State="AtInput" BoolValue="false"/>
            <Condition Resource="Self" State="PartPresent" BoolValue="false"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="AtInput" BoolValue="true"/>
            <Condition Resource="Self" State="PartPresent" BoolValue="true"/>
          </FinishedConditions>
        </SkillDefinition>
      </SkillDefinitions>
      <States>
        <State Name="Error" ID="-1"/>
        <State Name="Unknown" ID="0"/>
        <State Name="AtSeperation" ID="1"/>
        <State Name="AtInput" ID="2"/>
        <State Name="PartPresent" ID="3"/>
        <State Name="AreaOccupied" ID="4"/>
      </States>
    </Resource>
    <Resource Name="RIT" Type="Group">
      <SkillDefinitions>
        <SkillDefinition Name="Turn" Parameters="TurnValue" TimeRequired="300">
          <StartConditions>
            <Condition Resource="Self" State="IsMoving" BoolValue="false"/>
            <Condition Resource="Self" State="InPosition" BoolValue="true"/>
            <Condition Resource="Nest01" State="IsOccupied" BoolValue="true"/>
            <Condition Resource="Nest06" State="IsOccupied" BoolValue="false"/>
            <Condition Resource="Station01" State="ProcessFinished" BoolValue="true"/>
            <Condition Resource="Station02" State="ProcessFinished" BoolValue="true"/>
            <Condition Resource="Station03" State="ProcessFinished" BoolValue="true"/>
            <Condition Resource="Station04" State="ProcessFinished" BoolValue="true"/>
            <Condition Resource="Station05" State="ProcessFinished" BoolValue="true"/>
            <Condition Resource="Station06" State="ProcessFinished" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="IsMoving" BoolValue="false"/>
            <Condition Resource="Self" State="InPosition" BoolValue="true"/>
            <Condition Resource="Nest01" State="IsOccupied" BoolValue="false"/>
            <Condition Resource="Station01" State="ProcessFinished" BoolValue="false"/>
            <Condition Resource="Station02" State="ProcessFinished" BoolValue="false"/>
            <Condition Resource="Station03" State="ProcessFinished" BoolValue="false"/>
            <Condition Resource="Station04" State="ProcessFinished" BoolValue="false"/>
            <Condition Resource="Station05" State="ProcessFinished" BoolValue="false"/>
            <Condition Resource="Station06" State="ProcessFinished" BoolValue="false"/>
          </FinishedConditions>
        </SkillDefinition>
        <SkillDefinition Name="ErrorQuit" TimeRequired="500">
          <StartConditions>
            <Condition Resource="Self" State="Error" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Error" BoolValue="false"/>
          </FinishedConditions>
        </SkillDefinition>
      </SkillDefinitions>
      <States>
        <State ID="-1" Name="Error"/>
        <State ID="0" Name="InPosition"/>
        <State ID="1" Name="Moving"/>
      </States>
    </Resource>
    <Resource Name ="Station00" Type="Group">
      <SkillDefinitions>
        <SkillDefinition Name="Start" TimeRequired="1000">
          <StartConditions>
            <Condition Resource="Machine" State="Running" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Self" State="Running" BoolValue="true"/>
          </FinishedConditions>
        </SkillDefinition>
      </SkillDefinitions>
      <States>
        <State Name="Running" ID="1"/>
        <State Name="ProcessStarted" ID="2"/>
        <State Name="ProcessFinished" ID="3"/>
      </States>
    </Resource>
    <Resource Name ="Station01" Type="Group">
      <SkillDefinitions>
        <SkillDefinition Name="Start" TimeRequired="1000">
          <StartConditions>
            <Condition Resource="Machine" State="Running" BoolValue="true"/>
          </StartConditions>
          <FinishedConditions>
            <Condition Resource="Nest01" State="Occupied" BoolValue="true"/>
          </FinishedConditions>
        </SkillDefinition>
